#!/bin/sh

#using examples from http://blog.lazyhacker.com/2015/03/automatically-start-minecraft-server-on.html
#thanks lazy hacker

cd ~/Desktop/Sekai

python ./update_sekai.py

tmux new-session -s sekai -d

tmux send -t sekai "java -Xms1G -Xmx3G -jar server.jar nogui" ENTER

#ava -Xms1G -Xmx3G -jar server.jar nogui

