#!/bin/sh

# using example from http://blog.lazyhacker.com/2015/03/automatically-start-minecraft-server-on.html

# cd directory of this script
cd $(dirname $0)

tmux send -t sekai "say stopping server" ENTER
tmux send -t sekai "save-all" ENTER
tmux send -t sekai "stop" ENTER
echo "Stopping sekai."
sleep 5

tmux kill-session -t sekai

